spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB  
  application:
    name: elegant-tex
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        javax.persistence.validation.mode: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.resend.com
    port: 587
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

server:
  port: ${SERVER_PORT:8080}
  servlet:
    multipart:
      enabled: true
    context-path: /api/v1

logging:
  level:
    org.springframework.security: INFO
    com.tripzin.eleganttex: INFO

app:
  frontend-url: ${APP_FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    allowed-file-types: jpg,jpeg,png,gif
    max-file-size: 20971520
    use-s3-storage: ${USE_S3_STORAGE:false}
    s3-bucket-name: ${S3_BUCKET_NAME:}
    s3-region: ${S3_REGION:us-east-1}
    s3-public-access: ${S3_PUBLIC_ACCESS:false}
    aws-access-key-id: ${AWS_ACCESS_KEY_ID:}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
