spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB  
  application:
    name: elegant-tex
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        javax.persistence.validation.mode: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.resend.com
    port: 587
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: false
  servlet:
    multipart:
      enabled: true
    context-path: /api/v1

logging:
  level:
    org.springframework.security: INFO
    com.tripzin.eleganttex: INFO

app:
  frontend-url: ${APP_FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    allowed-file-types: jpg,jpeg,png,gif
    max-file-size: 52428800  # 50MB in bytes
    use-s3-storage: ${USE_S3_STORAGE:false}
    s3-bucket-name: ${S3_BUCKET_NAME:}
    s3-region: ${S3_REGION:us-east-1}
    s3-public-access: ${S3_PUBLIC_ACCESS:false}
    aws-access-key-id: ${AWS_ACCESS_KEY_ID:}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  # Messaging Configuration
  messaging:
    webhook:
      base-url: ${MESSAGING_WEBHOOK_BASE_URL}
      verify-signatures: ${MESSAGING_WEBHOOK_VERIFY_SIGNATURES:true}
    rate-limiting:
      requests-per-minute: ${MESSAGING_RATE_LIMIT_REQUESTS_PER_MINUTE:60}
      max-retry-attempts: ${MESSAGING_MAX_RETRY_ATTEMPTS:3}
      retry-delay-seconds: ${MESSAGING_RETRY_DELAY_SECONDS:5}
    facebook:
      app-id: ${FACEBOOK_APP_ID:}
      app-secret: ${FACEBOOK_APP_SECRET:}
      graph-api-url: ${FACEBOOK_GRAPH_API_URL:https://graph.facebook.com}
      api-version: ${FACEBOOK_API_VERSION:v23.0}
      webhook-verify-token: ${FACEBOOK_WEBHOOK_VERIFY_TOKEN:}
    whatsapp:
      api-url: ${WHATSAPP_API_URL:https://graph.facebook.com}
      api-version: ${WHATSAPP_API_VERSION:v23.0}
      webhook-verify-token: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN:}
    processing:
      async-enabled: ${MESSAGING_ASYNC_PROCESSING:true}
      thread-pool-size: ${MESSAGING_THREAD_POOL_SIZE:10}
      queue-capacity: ${MESSAGING_QUEUE_CAPACITY:100}
