# application.yml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB  
  application:
    name: elegant-tex
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        javax.persistence.validation.mode: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: smtp.resend.com
    port: 587
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000  # 15 minutes in milliseconds
  refresh-token-expiration: 604800000  # 7 days in milliseconds

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    multipart:
      enabled: true
    context-path: /api/v1

# Logging Configuration
logging:
  level:
    org.springframework.security: INFO
    com.tripzin.eleganttex: DEBUG

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Application specific configuration
app:
  frontend-url: ${APP_FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  email:
    provider: ${EMAIL_PROVIDER:smtp}  # smtp or resend
    resend:
      api-key: ${RESEND_API_KEY:}
  file-storage:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    allowed-file-types: jpg,jpeg,png,gif
    max-file-size: 52428800  # 50MB in bytes
    # S3 Configuration
    use-s3-storage: ${USE_S3_STORAGE:false}
    s3-bucket-name: ${S3_BUCKET_NAME:}
    s3-region: ${S3_REGION:us-east-1}
    s3-public-access: ${S3_PUBLIC_ACCESS:false}
    aws-access-key-id: ${AWS_ACCESS_KEY_ID:}
    aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
