global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elegant-tex'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
